/* AUTO GENERATED BY make. DO NOT EDIT! */

#define RELEASE "0.99"
#define BLAME "root@libxenon i686"
#define DATE "2011-12-17"
#define GITREV ""

#define VERSION RELEASE "-git-" GITREV
#define LONGVERSION VERSION " " DATE " (" BLAME ")"
